packages:
  - 'frontend'
  - 'backend'

packageExtensions:
  "@tailwindcss/oxide":
    dependencies:
      esbuild: ^0.20.0 # or your desired version
  esbuild:
    scripts:
      postinstall: "node ./bin/esbuild"


